/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'nios2_gen2_0' in SOPC Builder design 'nios_setup'
 * SOPC Builder design path: H:/Real_Time/Fichiers_a_fournir/nios_setup.sopcinfo
 *
 * Generated: Thu Oct 16 13:45:14 CEST 2025
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x08010820
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 50000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "tiny"
#define ALT_CPU_DATA_ADDR_WIDTH 0x1c
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x04000020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 50000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 0
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 0
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_ICACHE_SIZE 0
#define ALT_CPU_INST_ADDR_WIDTH 0x1c
#define ALT_CPU_NAME "nios2_gen2_0"
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x04000000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x08010820
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 50000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "tiny"
#define NIOS2_DATA_ADDR_WIDTH 0x1c
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x04000020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 0
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 0
#define NIOS2_ICACHE_LINE_SIZE_LOG2 0
#define NIOS2_ICACHE_SIZE 0
#define NIOS2_INST_ADDR_WIDTH 0x1c
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x04000000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_NEW_SDRAM_CONTROLLER
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_PIO
#define __ALTERA_AVALON_TIMER
#define __ALTERA_MODULAR_ADC
#define __ALTERA_NIOS2_GEN2
#define __SEVEN_SEG


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "MAX 10"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart_0"
#define ALT_STDERR_BASE 0x8011278
#define ALT_STDERR_DEV jtag_uart_0
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart_0"
#define ALT_STDIN_BASE 0x8011278
#define ALT_STDIN_DEV jtag_uart_0
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart_0"
#define ALT_STDOUT_BASE 0x8011278
#define ALT_STDOUT_DEV jtag_uart_0
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "nios_setup"


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 32
#define ALT_SYS_CLK ONE_SEC_TIMER
#define ALT_TIMESTAMP_CLK none


/*
 * jtag_uart_0 configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart_0 altera_avalon_jtag_uart
#define JTAG_UART_0_BASE 0x8011278
#define JTAG_UART_0_IRQ 0
#define JTAG_UART_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_0_NAME "/dev/jtag_uart_0"
#define JTAG_UART_0_READ_DEPTH 64
#define JTAG_UART_0_READ_THRESHOLD 8
#define JTAG_UART_0_SPAN 8
#define JTAG_UART_0_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_0_WRITE_DEPTH 64
#define JTAG_UART_0_WRITE_THRESHOLD 8


/*
 * key configuration
 *
 */

#define ALT_MODULE_CLASS_key altera_avalon_pio
#define KEY_BASE 0x8011240
#define KEY_BIT_CLEARING_EDGE_REGISTER 0
#define KEY_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KEY_CAPTURE 0
#define KEY_DATA_WIDTH 2
#define KEY_DO_TEST_BENCH_WIRING 0
#define KEY_DRIVEN_SIM_VALUE 0
#define KEY_EDGE_TYPE "NONE"
#define KEY_FREQ 50000000
#define KEY_HAS_IN 1
#define KEY_HAS_OUT 0
#define KEY_HAS_TRI 0
#define KEY_IRQ 3
#define KEY_IRQ_INTERRUPT_CONTROLLER_ID 0
#define KEY_IRQ_TYPE "LEVEL"
#define KEY_NAME "/dev/key"
#define KEY_RESET_VALUE 0
#define KEY_SPAN 16
#define KEY_TYPE "altera_avalon_pio"


/*
 * leds configuration
 *
 */

#define ALT_MODULE_CLASS_leds altera_avalon_pio
#define LEDS_BASE 0x8011220
#define LEDS_BIT_CLEARING_EDGE_REGISTER 0
#define LEDS_BIT_MODIFYING_OUTPUT_REGISTER 1
#define LEDS_CAPTURE 0
#define LEDS_DATA_WIDTH 10
#define LEDS_DO_TEST_BENCH_WIRING 0
#define LEDS_DRIVEN_SIM_VALUE 0
#define LEDS_EDGE_TYPE "NONE"
#define LEDS_FREQ 50000000
#define LEDS_HAS_IN 0
#define LEDS_HAS_OUT 1
#define LEDS_HAS_TRI 0
#define LEDS_IRQ -1
#define LEDS_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LEDS_IRQ_TYPE "NONE"
#define LEDS_NAME "/dev/leds"
#define LEDS_RESET_VALUE 0
#define LEDS_SPAN 32
#define LEDS_TYPE "altera_avalon_pio"


/*
 * modular_adc_0_sample_store_csr configuration
 *
 */

#define ALT_MODULE_CLASS_modular_adc_0_sample_store_csr altera_modular_adc
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_BASE 0x8011000
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CORE_VARIANT 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_LENGTH 64
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_0 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_1 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_10 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_11 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_12 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_13 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_14 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_15 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_16 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_17 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_18 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_19 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_2 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_20 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_21 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_22 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_23 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_24 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_25 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_26 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_27 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_28 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_29 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_3 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_30 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_31 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_32 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_33 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_34 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_35 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_36 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_37 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_38 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_39 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_4 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_40 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_41 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_42 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_43 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_44 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_45 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_46 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_47 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_48 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_49 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_5 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_50 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_51 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_52 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_53 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_54 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_55 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_56 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_57 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_58 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_59 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_6 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_60 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_61 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_62 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_63 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_7 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_8 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_9 "TSD"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_DUAL_ADC_MODE 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_IRQ 2
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_IRQ_INTERRUPT_CONTROLLER_ID 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_IS_THIS_FIRST_OR_SECOND_ADC 1
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_NAME "/dev/modular_adc_0_sample_store_csr"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_PRESCALER_CH16 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_PRESCALER_CH8 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_REFSEL "External VREF"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_SPAN 512
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_TYPE "altera_modular_adc"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH0 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH1 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH10 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH11 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH12 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH13 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH14 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH15 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH16 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH2 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH3 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH4 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH5 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH6 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH7 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH8 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH9 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_TSD 1
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_VREF 2.5


/*
 * modular_adc_0_sequencer_csr configuration
 *
 */

#define ALT_MODULE_CLASS_modular_adc_0_sequencer_csr altera_modular_adc
#define MODULAR_ADC_0_SEQUENCER_CSR_BASE 0x8011270
#define MODULAR_ADC_0_SEQUENCER_CSR_CORE_VARIANT 0
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_LENGTH 64
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_0 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_1 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_10 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_11 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_12 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_13 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_14 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_15 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_16 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_17 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_18 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_19 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_2 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_20 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_21 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_22 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_23 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_24 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_25 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_26 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_27 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_28 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_29 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_3 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_30 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_31 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_32 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_33 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_34 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_35 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_36 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_37 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_38 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_39 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_4 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_40 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_41 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_42 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_43 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_44 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_45 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_46 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_47 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_48 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_49 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_5 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_50 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_51 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_52 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_53 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_54 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_55 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_56 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_57 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_58 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_59 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_6 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_60 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_61 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_62 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_63 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_7 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_8 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_9 "TSD"
#define MODULAR_ADC_0_SEQUENCER_CSR_DUAL_ADC_MODE 0
#define MODULAR_ADC_0_SEQUENCER_CSR_IRQ -1
#define MODULAR_ADC_0_SEQUENCER_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MODULAR_ADC_0_SEQUENCER_CSR_IS_THIS_FIRST_OR_SECOND_ADC 1
#define MODULAR_ADC_0_SEQUENCER_CSR_NAME "/dev/modular_adc_0_sequencer_csr"
#define MODULAR_ADC_0_SEQUENCER_CSR_PRESCALER_CH16 0
#define MODULAR_ADC_0_SEQUENCER_CSR_PRESCALER_CH8 0
#define MODULAR_ADC_0_SEQUENCER_CSR_REFSEL "External VREF"
#define MODULAR_ADC_0_SEQUENCER_CSR_SPAN 8
#define MODULAR_ADC_0_SEQUENCER_CSR_TYPE "altera_modular_adc"
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH0 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH1 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH10 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH11 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH12 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH13 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH14 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH15 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH16 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH2 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH3 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH4 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH5 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH6 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH7 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH8 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH9 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_TSD 1
#define MODULAR_ADC_0_SEQUENCER_CSR_VREF 2.5


/*
 * onchip_memory2_0 configuration
 *
 */

#define ALT_MODULE_CLASS_onchip_memory2_0 altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_0_BASE 0x8008000
#define ONCHIP_MEMORY2_0_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_0_DUAL_PORT 0
#define ONCHIP_MEMORY2_0_GUI_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY2_0_INIT_CONTENTS_FILE "nios_setup_onchip_memory2_0"
#define ONCHIP_MEMORY2_0_INIT_MEM_CONTENT 0
#define ONCHIP_MEMORY2_0_INSTANCE_ID "NONE"
#define ONCHIP_MEMORY2_0_IRQ -1
#define ONCHIP_MEMORY2_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ONCHIP_MEMORY2_0_NAME "/dev/onchip_memory2_0"
#define ONCHIP_MEMORY2_0_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_0_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY2_0_READ_DURING_WRITE_MODE "DONT_CARE"
#define ONCHIP_MEMORY2_0_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY2_0_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_0_SIZE_VALUE 32768
#define ONCHIP_MEMORY2_0_SPAN 32768
#define ONCHIP_MEMORY2_0_TYPE "altera_avalon_onchip_memory2"
#define ONCHIP_MEMORY2_0_WRITABLE 1


/*
 * one_sec_timer configuration
 *
 */

#define ALT_MODULE_CLASS_one_sec_timer altera_avalon_timer
#define ONE_SEC_TIMER_ALWAYS_RUN 0
#define ONE_SEC_TIMER_BASE 0x8011200
#define ONE_SEC_TIMER_COUNTER_SIZE 32
#define ONE_SEC_TIMER_FIXED_PERIOD 0
#define ONE_SEC_TIMER_FREQ 50000000
#define ONE_SEC_TIMER_IRQ 1
#define ONE_SEC_TIMER_IRQ_INTERRUPT_CONTROLLER_ID 0
#define ONE_SEC_TIMER_LOAD_VALUE 49999999
#define ONE_SEC_TIMER_MULT 1.0
#define ONE_SEC_TIMER_NAME "/dev/one_sec_timer"
#define ONE_SEC_TIMER_PERIOD 1
#define ONE_SEC_TIMER_PERIOD_UNITS "s"
#define ONE_SEC_TIMER_RESET_OUTPUT 0
#define ONE_SEC_TIMER_SNAPSHOT 1
#define ONE_SEC_TIMER_SPAN 32
#define ONE_SEC_TIMER_TICKS_PER_SEC 1
#define ONE_SEC_TIMER_TIMEOUT_PULSE_OUTPUT 0
#define ONE_SEC_TIMER_TYPE "altera_avalon_timer"


/*
 * sdram configuration
 *
 */

#define ALT_MODULE_CLASS_sdram altera_avalon_new_sdram_controller
#define SDRAM_BASE 0x4000000
#define SDRAM_CAS_LATENCY 3
#define SDRAM_CONTENTS_INFO
#define SDRAM_INIT_NOP_DELAY 0.0
#define SDRAM_INIT_REFRESH_COMMANDS 2
#define SDRAM_IRQ -1
#define SDRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SDRAM_IS_INITIALIZED 1
#define SDRAM_NAME "/dev/sdram"
#define SDRAM_POWERUP_DELAY 100.0
#define SDRAM_REFRESH_PERIOD 7.8125
#define SDRAM_REGISTER_DATA_IN 1
#define SDRAM_SDRAM_ADDR_WIDTH 0x19
#define SDRAM_SDRAM_BANK_WIDTH 2
#define SDRAM_SDRAM_COL_WIDTH 10
#define SDRAM_SDRAM_DATA_WIDTH 16
#define SDRAM_SDRAM_NUM_BANKS 4
#define SDRAM_SDRAM_NUM_CHIPSELECTS 1
#define SDRAM_SDRAM_ROW_WIDTH 13
#define SDRAM_SHARED_DATA 0
#define SDRAM_SIM_MODEL_BASE 0
#define SDRAM_SPAN 67108864
#define SDRAM_STARVATION_INDICATOR 0
#define SDRAM_TRISTATE_BRIDGE_SLAVE ""
#define SDRAM_TYPE "altera_avalon_new_sdram_controller"
#define SDRAM_T_AC 5.4
#define SDRAM_T_MRD 3
#define SDRAM_T_RCD 15.0
#define SDRAM_T_RFC 70.0
#define SDRAM_T_RP 15.0
#define SDRAM_T_WR 14.0


/*
 * seven_seg_0 configuration
 *
 */

#define ALT_MODULE_CLASS_seven_seg_0 seven_seg
#define SEVEN_SEG_0_BASE 0x8011260
#define SEVEN_SEG_0_IRQ -1
#define SEVEN_SEG_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SEVEN_SEG_0_NAME "/dev/seven_seg_0"
#define SEVEN_SEG_0_SPAN 16
#define SEVEN_SEG_0_TYPE "seven_seg"


/*
 * sw configuration
 *
 */

#define ALT_MODULE_CLASS_sw altera_avalon_pio
#define SW_BASE 0x8011250
#define SW_BIT_CLEARING_EDGE_REGISTER 0
#define SW_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SW_CAPTURE 1
#define SW_DATA_WIDTH 10
#define SW_DO_TEST_BENCH_WIRING 0
#define SW_DRIVEN_SIM_VALUE 0
#define SW_EDGE_TYPE "RISING"
#define SW_FREQ 50000000
#define SW_HAS_IN 1
#define SW_HAS_OUT 0
#define SW_HAS_TRI 0
#define SW_IRQ -1
#define SW_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SW_IRQ_TYPE "NONE"
#define SW_NAME "/dev/sw"
#define SW_RESET_VALUE 0
#define SW_SPAN 16
#define SW_TYPE "altera_avalon_pio"


/*
 * ucosii configuration
 *
 */

#define OS_ARG_CHK_EN 1
#define OS_CPU_HOOKS_EN 1
#define OS_DEBUG_EN 1
#define OS_EVENT_NAME_SIZE 32
#define OS_FLAGS_NBITS 16
#define OS_FLAG_ACCEPT_EN 1
#define OS_FLAG_DEL_EN 1
#define OS_FLAG_EN 1
#define OS_FLAG_NAME_SIZE 32
#define OS_FLAG_QUERY_EN 1
#define OS_FLAG_WAIT_CLR_EN 1
#define OS_LOWEST_PRIO 20
#define OS_MAX_EVENTS 60
#define OS_MAX_FLAGS 20
#define OS_MAX_MEM_PART 60
#define OS_MAX_QS 20
#define OS_MAX_TASKS 10
#define OS_MBOX_ACCEPT_EN 1
#define OS_MBOX_DEL_EN 1
#define OS_MBOX_EN 1
#define OS_MBOX_POST_EN 1
#define OS_MBOX_POST_OPT_EN 1
#define OS_MBOX_QUERY_EN 1
#define OS_MEM_EN 1
#define OS_MEM_NAME_SIZE 32
#define OS_MEM_QUERY_EN 1
#define OS_MUTEX_ACCEPT_EN 1
#define OS_MUTEX_DEL_EN 1
#define OS_MUTEX_EN 1
#define OS_MUTEX_QUERY_EN 1
#define OS_Q_ACCEPT_EN 1
#define OS_Q_DEL_EN 1
#define OS_Q_EN 1
#define OS_Q_FLUSH_EN 1
#define OS_Q_POST_EN 1
#define OS_Q_POST_FRONT_EN 1
#define OS_Q_POST_OPT_EN 1
#define OS_Q_QUERY_EN 1
#define OS_SCHED_LOCK_EN 1
#define OS_SEM_ACCEPT_EN 1
#define OS_SEM_DEL_EN 1
#define OS_SEM_EN 1
#define OS_SEM_QUERY_EN 1
#define OS_SEM_SET_EN 1
#define OS_TASK_CHANGE_PRIO_EN 1
#define OS_TASK_CREATE_EN 1
#define OS_TASK_CREATE_EXT_EN 1
#define OS_TASK_DEL_EN 1
#define OS_TASK_IDLE_STK_SIZE 512
#define OS_TASK_NAME_SIZE 32
#define OS_TASK_PROFILE_EN 1
#define OS_TASK_QUERY_EN 1
#define OS_TASK_STAT_EN 1
#define OS_TASK_STAT_STK_CHK_EN 1
#define OS_TASK_STAT_STK_SIZE 512
#define OS_TASK_SUSPEND_EN 1
#define OS_TASK_SW_HOOK_EN 1
#define OS_TASK_TMR_PRIO 0
#define OS_TASK_TMR_STK_SIZE 512
#define OS_THREAD_SAFE_NEWLIB 1
#define OS_TICKS_PER_SEC ONE_SEC_TIMER_TICKS_PER_SEC
#define OS_TICK_STEP_EN 1
#define OS_TIME_DLY_HMSM_EN 1
#define OS_TIME_DLY_RESUME_EN 1
#define OS_TIME_GET_SET_EN 1
#define OS_TIME_TICK_HOOK_EN 1
#define OS_TMR_CFG_MAX 16
#define OS_TMR_CFG_NAME_SIZE 16
#define OS_TMR_CFG_TICKS_PER_SEC 10
#define OS_TMR_CFG_WHEEL_SIZE 2
#define OS_TMR_EN 0

#endif /* __SYSTEM_H_ */
